---
- apt: update_cache=yes

# Install the package "mysql"
- apt: name={{item}} state=present
  with_items:
   - mysql-client
   - tree
   - mosh
   - lynx
   - unzip
   - whois
   - zip
   - openjdk-7-jdk

