---
#- apt: update_cache=yes

- name: Install the package {{ item }}
  apt: name={{item}} state=present
  with_items:
   - mysql-client
   - tree
   - mosh
   - lynx
   - unzip
   - whois
   - zip
   - git
   - openjdk-7-jdk

